# Integration Test Execution Script
# For MingGoRTS Project
# Usage: Run this script in PowerShell to execute integration tests

param(
    [string]$ProjectPath = "C:\\HW\\MingGoRTS",
    [string]$UEEditorPath = "C:\Program Files\Epic Games\UE_5.7\Engine\Binaries\Win64\UnrealEditor.exe",
    [string]$TestMap = "/Game/Maps/TestMap",
    [switch]$RunAllPhases,
    [switch]$RunBasicIntegration,
    [switch]$RunDataFlow,
    [switch]$RunPerformance,
    [switch]$RunUserExperience,
    [switch]$RunCompatibility,
    [switch]$RunFinalValidation,
    [switch]$GenerateReport,
    [string]$OutputPath = "$PSScriptRoot\\TestResults"
)

# Create output directory if it doesn't exist
if (-not (Test-Path $OutputPath)) {
    New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
}

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$LogFile = "$OutputPath\\IntegrationTest_$timestamp.log"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $logEntry = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$Level] $Message"
    Write-Host $logEntry
    Add-Content -Path $LogFile -Value $logEntry
}

function Start-IntegrationTest {
    param(
        [string]$Phase,
        [string]$TestFlags
    )
    
    Write-Log "Starting Integration Test - Phase: $Phase" "INFO"
    
    # Build command arguments for UE automated testing
    $arguments = @(
        $ProjectPath + "\\MingGoRTS.uproject"
        $TestMap
        "-ExecCmds=Automation RunTests MingGoRTS.Integration.$Phase"
        "-log"
        "-TestExit=Automation Test Queue Empty"
        "- unattended"
        "-nopause"
        "-nosplash"
        "-TestOutputName=$OutputPath\\TestOutput_$Phase_$timestamp"
    )
    
    if ($TestFlags) {
        $arguments += $TestFlags
    }
    
    try {
        Write-Log "Executing: $UEEditorPath $arguments" "DEBUG"
        $process = Start-Process -FilePath $UEEditorPath -ArgumentList $arguments -Wait -PassThru -NoNewWindow
        
        if ($process.ExitCode -eq 0) {
            Write-Log "Phase $Phase completed successfully" "SUCCESS"
            return $true
        } else {
            Write-Log "Phase $Phase failed with exit code: $($process.ExitCode)" "ERROR"
            return $false
        }
    }
    catch {
        Write-Log "Error running phase $Phase`: $_" "ERROR"
        return $false
    }
}

function Get-TestResults {
    param([string]$Phase)
    
    $resultFile = "$OutputPath\\TestOutput_$Phase_$timestamp.json"
    
    if (Test-Path $resultFile) {
        try {
            $results = Get-Content $resultFile | ConvertFrom-Json
            return $results
        }
        catch {
            Write-Log "Error parsing results for phase $Phase`: $_" "ERROR"
            return $null
        }
    }
    
    return $null
}

function Export-TestReport {
    param(
        [array]$Results,
        [string]$ReportPath
    )
    
    $report = @"
# MingGoRTS Integration Test Report
Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

## Summary
Total Phases: $($Results.Count)
Passed: $($Results | Where-Object { $_.Passed } | Measure-Object | Select-Object -ExpandProperty Count)
Failed: $($Results | Where-Object { -not $_.Passed } | Measure-Object | Select-Object -ExpandProperty Count)

## Detailed Results

"@
    
    foreach ($result in $Results) {
        $status = if ($result.Passed) { "??PASSED" } else { "??FAILED" }
        $report += @"
### $($result.Phase) - $status
- Execution Time: $($result.ExecutionTime) seconds
- Tests Run: $($result.TestsRun)
- Tests Passed: $($result.TestsPassed)
- Tests Failed: $($result.TestsFailed)

"@
        
        if ($result.Errors.Count -gt 0) {
            $report += "#### Errors:\n"
            foreach ($error in $result.Errors) {
                $report += "- $error\n"
            }
            $report += "\n"
        }
    }
    
    $report += @"
## Recommendations

1. Review failed test cases and fix underlying issues
2. Re-run failed phases individually using the -Run<Phase> switches
3. Check UE logs for detailed error information
4. Ensure all subsystems are properly initialized before running tests

---
Report generated by MingGoRTS Integration Test Framework
"@
    
    $report | Out-File -FilePath $ReportPath -Encoding UTF8
    Write-Log "Test report exported to: $ReportPath" "INFO"
}

# Main execution logic
Write-Log "=== MingGoRTS Integration Test Execution Started ===" "INFO"
Write-Log "Project Path: $ProjectPath" "INFO"
Write-Log "Output Path: $OutputPath" "INFO"

$testResults = @()

# Determine which phases to run
$phasesToRun = @()

if ($RunAllPhases -or 
    (-not $RunBasicIntegration -and -not $RunDataFlow -and -not $RunPerformance -and 
     -not $RunUserExperience -and -not $RunCompatibility -and -not $RunFinalValidation)) {
    $phasesToRun = @("BasicIntegration", "DataFlow", "Performance", "UserExperience", "Compatibility", "FinalValidation")
} else {
    if ($RunBasicIntegration) { $phasesToRun += "BasicIntegration" }
    if ($RunDataFlow) { $phasesToRun += "DataFlow" }
    if ($RunPerformance) { $phasesToRun += "Performance" }
    if ($RunUserExperience) { $phasesToRun += "UserExperience" }
    if ($RunCompatibility) { $phasesToRun += "Compatibility" }
    if ($RunFinalValidation) { $phasesToRun += "FinalValidation" }
}

Write-Log "Phases to run: $($phasesToRun -join ', ')" "INFO"

# Run each phase
foreach ($phase in $phasesToRun) {
    $startTime = Get-Date
    $passed = Start-IntegrationTest -Phase $phase
    $endTime = Get-Date
    $executionTime = ($endTime - $startTime).TotalSeconds
    
    $results = Get-TestResults -Phase $phase
    
    $testResults += [PSCustomObject]@{
        Phase = $phase
        Passed = $passed
        ExecutionTime = [math]::Round($executionTime, 2)
        TestsRun = if ($results) { $results.TotalTests } else { 0 }
        TestsPassed = if ($results) { $results.PassedTests } else { 0 }
        TestsFailed = if ($results) { $results.FailedTests } else { 0 }
        Errors = if ($results) { $results.Errors } else { @() }
    }
}

# Generate report if requested
if ($GenerateReport -or $RunAllPhases) {
    $reportPath = "$OutputPath\\IntegrationTestReport_$timestamp.md"
    Export-TestReport -Results $testResults -ReportPath $reportPath
}

# Summary
$totalPassed = ($testResults | Where-Object { $_.Passed } | Measure-Object).Count
$totalFailed = ($testResults | Where-Object { -not $_.Passed } | Measure-Object).Count

Write-Log "=== Integration Test Execution Completed ===" "INFO"
Write-Log "Total Phases: $($testResults.Count)" "INFO"
Write-Log "Passed: $totalPassed" "SUCCESS"
Write-Log "Failed: $totalFailed" $(if ($totalFailed -gt 0) { "ERROR" } else { "INFO" })

if ($totalFailed -gt 0) {
    exit 1
} else {
    exit 0
}

