#Requires -Version 5.1
# MingGoRTS Final Clean Fix - IDE Compatible Version
# This script removes all characters that trigger IDE warnings

param(
    [string]$ProjectRoot = "f:\MingGoRTS"
)

$ToolsPath = Join-Path $ProjectRoot "Tools"
$ReportsPath = Join-Path $ProjectRoot "Reports"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$Timestamp] [$Level] $Message"
}

function Remove-ProblematicChars {
    param([string]$FilePath)

    $Content = Get-Content -Path $FilePath -Raw -Encoding UTF8
    $Original = $Content
    $Changes = 0

    # List of Unicode characters to replace
    $Replacements = @(
        @{ Find = [char]0x2014; Replace = "--"; Name = "Em dash" },
        @{ Find = [char]0x2013; Replace = "-"; Name = "En dash" },
        @{ Find = [char]0x201C; Replace = '"'; Name = "Left double quote" },
        @{ Find = [char]0x201D; Replace = '"'; Name = "Right double quote" },
        @{ Find = [char]0x2018; Replace = "'"; Name = "Left single quote" },
        @{ Find = [char]0x2019; Replace = "'"; Name = "Right single quote" },
        @{ Find = [char]0x2026; Replace = "..."; Name = "Ellipsis" },
        @{ Find = [char]0x2022; Replace = "-"; Name = "Bullet" },
        @{ Find = [char]0x200B; Replace = ""; Name = "Zero width space" },
        @{ Find = [char]0x200C; Replace = ""; Name = "Zero width non-joiner" },
        @{ Find = [char]0x200D; Replace = ""; Name = "Zero width joiner" },
        @{ Find = [char]0xFEFF; Replace = ""; Name = "BOM" }
    )

    foreach ($Rep in $Replacements) {
        if ($Content -match [regex]::Escape($Rep.Find)) {
            $Content = $Content -replace [regex]::Escape($Rep.Find), $Rep.Replace
            $Changes++
        }
    }

    # Replace box drawing characters
    for ($i = 0x2500; $i -le 0x257F; $i++) {
        $Char = [char]$i
        if ($Content -match $Char) {
            $Content = $Content -replace [regex]::Escape($Char), "="
            $Changes++
        }
    }

    # Replace emoji
    for ($i = 0x1F600; $i -le 0x1F64F; $i++) {
        $Char = [char]::ConvertFromUtf32($i)
        if ($Content -match $Char) {
            $Content = $Content -replace [regex]::Escape($Char), ""
            $Changes++
        }
    }

    # Clean line endings and trailing whitespace
    $Content = $Content -replace "\r?\n", "`n" -replace "`n", "`r`n"
    $Lines = $Content -split "`r`n"
    $CleanLines = foreach ($Line in $Lines) { $Line -replace "\s+$", "" }
    $Content = $CleanLines -join "`r`n"
    $Content = $Content -replace "(\r\n)+$", "`r`n"

    if ($Content -ne $Original) {
        $BackupPath = $FilePath + ".clean." + (Get-Date -Format 'yyyyMMddHHmmss') + ".bak"
        Copy-Item -Path $FilePath -Destination $BackupPath -Force
        [System.IO.File]::WriteAllText($FilePath, $Content, [System.Text.Encoding]::UTF8)
        return @{ Fixed = $true; Changes = $Changes; Backup = $BackupPath }
    }

    return @{ Fixed = $false; Changes = 0; Backup = $null }
}

# Main
Write-Log "Starting Final Clean Fix..."
Write-Log "Project Root: $ProjectRoot"

$Scripts = Get-ChildItem -Path $ToolsPath -Recurse -Include "*.ps1" -File -ErrorAction SilentlyContinue
Write-Log "Found $($Scripts.Count) PowerShell scripts"

$FixedCount = 0
$TotalChanges = 0

foreach ($Script in $Scripts) {
    $RelativePath = $Script.FullName.Substring($ProjectRoot.Length + 1)
    Write-Log "Processing: $RelativePath"

    $Result = Remove-ProblematicChars -FilePath $Script.FullName

    if ($Result.Fixed) {
        Write-Log "Fixed $($Result.Changes) issues" "SUCCESS"
        $FixedCount++
        $TotalChanges += $Result.Changes
    }
}

# Report
$ReportFile = Join-Path $ReportsPath ("FinalCleanFix_Report_" + (Get-Date -Format 'yyyyMMdd_HHmmss') + ".md")
$Report = @"
# Final Clean Fix Report

**Generated**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Summary

- Scripts Scanned: $($Scripts.Count)
- Scripts Fixed: $FixedCount
- Total Changes: $TotalChanges

## Details

All problematic characters have been removed:
- Smart quotes replaced with straight quotes
- Em/en dashes replaced with hyphens
- Unicode box characters replaced with ASCII
- Emoji characters removed
- Zero-width characters removed
- Line endings normalized

---
*Generated by Final-CleanFix.ps1*
"@
$Report | Set-Content -Path $ReportFile -Encoding UTF8

Write-Log ""
Write-Log "========================================"
Write-Log "Final Clean Fix Complete!"
Write-Log "========================================"
Write-Log "Scripts scanned: $($Scripts.Count)"
Write-Log "Scripts fixed: $FixedCount"
Write-Log "Total changes: $TotalChanges"
Write-Log "Report: $ReportFile"
