-- V1: cards + rosters 表——對齊 Card/Roster entity 的 Hibernate 映射
CREATE TABLE cards (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    schema_version VARCHAR(255),
    payload CLOB NOT NULL
);

CREATE TABLE rosters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_version VARCHAR(255),
    entry_count INTEGER,
    saved_at TIMESTAMP(6) WITH TIME ZONE,
    payload CLOB NOT NULL
);
