-- V1: replay 表——對齊 Replay entity 的 Hibernate 映射
-- (Instant → timestamp(6) with time zone;@Lob String → clob;
--  camelCase → snake_case)
CREATE TABLE replays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_version VARCHAR(255),
    event_count INTEGER,
    uploaded_at TIMESTAMP(6) WITH TIME ZONE,
    payload CLOB NOT NULL
);
