#include "MingAutoSceneGenerator.h"
#include "MingAIContentManager.h"
#include "MingAIGeneratedContentSystem.h"
#include "MingAIContentRenderer.h"
#include "Engine/World.h"
#include "Engine/Engine.h"
#include "HAL/PlatformFilemanager.h"
#include "Misc/Paths.h"
#include "Misc/DateTime.h"
#include "Kismet/KismetSystemLibrary.h"

UMingAutoSceneGenerator::UMingAutoSceneGenerator()
    : bIsInitialized(false)
    , bPreviewActive(false)
    , TotalSceneCount(0)
    , TotalGenerationTime(0.0f)
    , DefaultQuality(EGenerationQuality::Standard)
    , DefaultStyle(ESceneStyle::Realistic)
    , OutputDirectory(TEXT("/Game/AutoGenerated/Scenes/"))
{
}

void UMingAutoSceneGenerator::InitializeAutoSceneGenerator()
{
    if (bIsInitialized)
    {
        UE_LOG(LogTemp, Warning, TEXT("Auto Scene Generator already initialized"));
        return;
    }

    // 初始化AI內容管理器
    AIContentManager = NewObject<UMingAIContentManager>();
    if (AIContentManager)
    {
        AIContentManager->InitializeAIContentManager();
    }

    // 加載默認模板
    LoadDefaultTemplates();

    // 加載場景數據
    LoadSceneData();

    bIsInitialized = true;
    UE_LOG(LogTemp, Log, TEXT("Auto Scene Generator initialized"));
}

FString UMingAutoSceneGenerator::GenerateScene(const FSceneRequirement& Requirements)
{
    if (!bIsInitialized)
    {
        UE_LOG(LogTemp, Error, TEXT("Auto Scene Generator not initialized"));
        return TEXT("");
    }

    FString SceneName = GenerateUniqueSceneName();
    
    // 創建場景記錄
    FGeneratedScene NewScene;
    NewScene.SceneName = SceneName;
    NewScene.ScenePath = GetScenePath(SceneName);
    NewScene.bIsComplete = false;
    NewScene.GenerationProgress = 0.0f;
    NewScene.GenerationTime = FDateTime::Now();
    
    GeneratedScenes.Add(SceneName, NewScene);
    
    // 通知開始生成
    NotifySceneGenerationStarted(SceneName, Requirements);
    
    // 開始異步生成
    AsyncTask(ENamedThreads::AnyBackgroundThreadNormalTask, [this, SceneName, Requirements]()
    {
        ProcessSceneGeneration(SceneName, Requirements);
    });
    
    return SceneName;
}

void UMingAutoSceneGenerator::GenerateSceneAsync(const FSceneRequirement& Requirements)
{
    GenerateScene(Requirements);
}

TArray<FString> UMingAutoSceneGenerator::GenerateMultipleScenes(const TArray<FSceneRequirement>& RequirementsList)
{
    TArray<FString> SceneNames;
    
    for (const FSceneRequirement& Requirements : RequirementsList)
    {
        FString SceneName = GenerateScene(Requirements);
        if (!SceneName.IsEmpty())
        {
            SceneNames.Add(SceneName);
        }
    }
    
    return SceneNames;
}

FSceneRequirement UMingAutoSceneGenerator::GetBattleSceneTemplate(const FString& BattleDescription)
{
    FSceneRequirement Requirements;
    Requirements.SceneType = ESceneType::Battle;
    Requirements.Complexity = ESceneComplexity::Complex;
    Requirements.Style = ESceneStyle::Realistic;
    Requirements.Theme = TEXT("Ming Dynasty Battle");
    Requirements.Description = BattleDescription.IsEmpty() ? TEXT("Epic Ming dynasty battlefield with warriors, flags, and war atmosphere") : BattleDescription;
    Requirements.Duration = 60.0f;
    Requirements.bHasCharacters = true;
    Requirements.bHasBuildings = false;
    Requirements.bHasEnvironment = true;
    Requirements.bHasEffects = true;
    
    // 設置所需資產
    Requirements.RequiredAssets = {
        EAIContentType::Image,
        EAIContentType::Music,
        EAIContentType::SoundEffect,
        EAIContentType::Mesh,
        EAIContentType::Texture,
        EAIContentType::Material
    };
    
    // 設置資產提示
    Requirements.AssetPrompts = {
        {EAIContentType::Image, TEXT("Ming dynasty battlefield with warriors and flags")},
        {EAIContentType::Music, TEXT("Epic battle orchestral music with Chinese instruments")},
        {EAIContentType::SoundEffect, TEXT("Battle sounds: swords clashing, war cries, drums")},
        {EAIContentType::Mesh, TEXT("Ming dynasty warrior character model")},
        {EAIContentType::Texture, TEXT("Battle terrain texture with mud and blood")},
        {EAIContentType::Material, TEXT("War-torn battlefield material")}
    };
    
    return Requirements;
}

FSceneRequirement UMingAutoSceneGenerator::GetVillageSceneTemplate(const FString& VillageTheme)
{
    FSceneRequirement Requirements;
    Requirements.SceneType = ESceneType::Village;
    Requirements.Complexity = ESceneComplexity::Medium;
    Requirements.Style = ESceneStyle::Realistic;
    Requirements.Theme = TEXT("Ming Dynasty Village");
    Requirements.Description = VillageTheme.IsEmpty() ? TEXT("Peaceful Ming dynasty village with traditional houses and daily life") : VillageTheme;
    Requirements.Duration = 30.0f;
    Requirements.bHasCharacters = true;
    Requirements.bHasBuildings = true;
    Requirements.bHasEnvironment = true;
    Requirements.bHasEffects = false;
    
    // 設置所需資產
    Requirements.RequiredAssets = {
        EAIContentType::Image,
        EAIContentType::Music,
        EAIContentType::SoundEffect,
        EAIContentType::Mesh,
        EAIContentType::Texture,
        EAIContentType::Material
    };
    
    // 設置資產提示
    Requirements.AssetPrompts = {
        {EAIContentType::Image, TEXT("Traditional Ming dynasty village with houses and streets")},
        {EAIContentType::Music, TEXT("Peaceful village ambient music with Chinese folk instruments")},
        {EAIContentType::SoundEffect, TEXT("Village sounds: people talking, animals, daily activities")},
        {EAIContentType::Mesh, TEXT("Traditional Chinese house building model")},
        {EAIContentType::Texture, TEXT("Wood and stone village texture")},
        {EAIContentType::Material, TEXT("Traditional Chinese building material")}
    };
    
    return Requirements;
}

FSceneRequirement UMingAutoSceneGenerator::GetPalaceSceneTemplate(const FString& PalaceStyle)
{
    FSceneRequirement Requirements;
    Requirements.SceneType = ESceneType::Palace;
    Requirements.Complexity = ESceneComplexity::Epic;
    Requirements.Style = ESceneStyle::Photorealistic;
    Requirements.Theme = TEXT("Ming Dynasty Palace");
    Requirements.Description = PalaceStyle.IsEmpty() ? TEXT("Magnificent Ming dynasty imperial palace with golden roofs and red walls") : PalaceStyle;
    Requirements.Duration = 45.0f;
    Requirements.bHasCharacters = true;
    Requirements.bHasBuildings = true;
    Requirements.bHasEnvironment = true;
    Requirements.bHasEffects = true;
    
    // 設置所需資產
    Requirements.RequiredAssets = {
        EAIContentType::Image,
        EAIContentType::Music,
        EAIContentType::SoundEffect,
        EAIContentType::Mesh,
        EAIContentType::Texture,
        EAIContentType::Material,
        EAIContentType::Animation
    };
    
    // 設置資產提示
    Requirements.AssetPrompts = {
        {EAIContentType::Image, TEXT("Ming dynasty imperial palace with golden roofs and red walls")},
        {EAIContentType::Music, TEXT("Imperial court music with traditional Chinese orchestra")},
        {EAIContentType::SoundEffect, TEXT("Palace sounds: court ceremonies, bells, wind chimes")},
        {EAIContentType::Mesh, TEXT("Imperial palace building complex model")},
        {EAIContentType::Texture, TEXT("Golden roof and red wall texture")},
        {EAIContentType::Material, TEXT("Luxurious imperial palace material")},
        {EAIContentType::Animation, TEXT("Court ceremony animation")}
    };
    
    return Requirements;
}

FSceneRequirement UMingAutoSceneGenerator::GetNatureSceneTemplate(ESceneType NatureType, const FString& Environment)
{
    FSceneRequirement Requirements;
    Requirements.SceneType = NatureType;
    Requirements.Complexity = ESceneComplexity::Medium;
    Requirements.Style = ESceneStyle::Photorealistic;
    Requirements.Theme = TEXT("Chinese Nature");
    Requirements.Description = Environment.IsEmpty() ? TEXT("Beautiful Chinese natural landscape") : Environment;
    Requirements.Duration = 30.0f;
    Requirements.bHasCharacters = false;
    Requirements.bHasBuildings = false;
    Requirements.bHasEnvironment = true;
    Requirements.bHasEffects = true;
    
    // 根據場景類型設置特定提示
    FString EnvironmentPrompt;
    switch (NatureType)
    {
        case ESceneType::Forest:
            EnvironmentPrompt = TEXT("Ancient Chinese bamboo forest with mist and sunlight");
            break;
        case ESceneType::Mountain:
            EnvironmentPrompt = TEXT("Majestic Chinese mountains with temples and clouds");
            break;
        case ESceneType::River:
            EnvironmentPrompt = TEXT("Peaceful Chinese river with boats and willow trees");
            break;
        case ESceneType::Desert:
            EnvironmentPrompt = TEXT("Chinese desert landscape with dunes and oasis");
            break;
        default:
            EnvironmentPrompt = Environment;
            break;
    }
    
    // 設置所需資產
    Requirements.RequiredAssets = {
        EAIContentType::Image,
        EAIContentType::Music,
        EAIContentType::SoundEffect,
        EAIContentType::Texture,
        EAIContentType::Material
    };
    
    // 設置資產提示
    Requirements.AssetPrompts = {
        {EAIContentType::Image, EnvironmentPrompt},
        {EAIContentType::Music, TEXT("Peaceful nature music with Chinese instruments")},
        {EAIContentType::SoundEffect, TEXT("Nature sounds: wind, water, birds")},
        {EAIContentType::Texture, TEXT("Natural environment texture")},
        {EAIContentType::Material, TEXT("Nature environment material")}
    };
    
    return Requirements;
}

TArray<FGeneratedScene> UMingAutoSceneGenerator::GetAllGeneratedScenes() const
{
    TArray<FGeneratedScene> AllScenes;
    
    for (const auto& ScenePair : GeneratedScenes)
    {
        AllScenes.Add(ScenePair.Value);
    }
    
    return AllScenes;
}

FGeneratedScene UMingAutoSceneGenerator::GetGeneratedScene(const FString& SceneName) const
{
    if (GeneratedScenes.Contains(SceneName))
    {
        return GeneratedScenes[SceneName];
    }
    
    return FGeneratedScene();
}

void UMingAutoSceneGenerator::DeleteGeneratedScene(const FString& SceneName)
{
    if (GeneratedScenes.Contains(SceneName))
    {
        GeneratedScenes.Remove(SceneName);
        
        // 刪除相關文件
        FString ScenePath = GetScenePath(SceneName);
        IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
        if (PlatformFile.DirectoryExists(*ScenePath))
        {
            PlatformFile.DeleteDirectoryRecursively(*ScenePath);
        }
        
        UE_LOG(LogTemp, Log, TEXT("Deleted generated scene: %s"), *SceneName);
    }
}

void UMingAutoSceneGenerator::LoadSceneIntoWorld(const FString& SceneName, UWorld* World)
{
    if (!World || !GeneratedScenes.Contains(SceneName))
    {
        UE_LOG(LogTemp, Warning, TEXT("Cannot load scene %s: invalid world or scene not found"), *SceneName);
        return;
    }
    
    const FGeneratedScene& Scene = GeneratedScenes[SceneName];
    
    // 加載場景配置
    if (AIContentManager)
    {
        AIContentManager->GenerateGameScene(Scene.SceneConfiguration.SceneDescription, Scene.SceneConfiguration);
    }
    
    UE_LOG(LogTemp, Log, TEXT("Loaded scene %s into world"), *SceneName);
}

void UMingAutoSceneGenerator::StartScenePreview(const FString& SceneName)
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        UE_LOG(LogTemp, Warning, TEXT("Scene %s not found for preview"), *SceneName);
        return;
    }
    
    CurrentPreviewScene = SceneName;
    
    if (AIContentManager)
    {
        AIContentManager->StartRealTimePreview();
    }
    
    bPreviewActive = true;
    
    UE_LOG(LogTemp, Log, TEXT("Started preview for scene: %s"), *SceneName);
}

void UMingAutoSceneGenerator::StopScenePreview()
{
    if (AIContentManager)
    {
        AIContentManager->StopRealTimePreview();
    }
    
    bPreviewActive = false;
    CurrentPreviewScene = TEXT("");
    
    UE_LOG(LogTemp, Log, TEXT("Stopped scene preview"));
}

void UMingAutoSceneGenerator::ExportScene(const FString& SceneName, const FString& ExportPath)
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        UE_LOG(LogTemp, Warning, TEXT("Scene %s not found for export"), *SceneName);
        return;
    }
    
    const FGeneratedScene& Scene = GeneratedScenes[SceneName];
    
    // 實現場景導出邏輯
    UE_LOG(LogTemp, Log, TEXT("Exported scene %s to %s"), *SceneName, *ExportPath);
}

void UMingAutoSceneGenerator::ExportSceneAsVideo(const FString& SceneName, float Duration, const FString& OutputPath)
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        UE_LOG(LogTemp, Warning, TEXT("Scene %s not found for video export"), *SceneName);
        return;
    }
    
    const FGeneratedScene& Scene = GeneratedScenes[SceneName];
    
    if (AIContentManager)
    {
        AIContentManager->GenerateCinematicScene(Scene.SceneConfiguration.SceneDescription, Duration);
    }
    
    UE_LOG(LogTemp, Log, TEXT("Exported scene %s as video to %s"), *SceneName, *OutputPath);
}

void UMingAutoSceneGenerator::GenerateSceneThumbnail(const FString& SceneName)
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        UE_LOG(LogTemp, Warning, TEXT("Scene %s not found for thumbnail generation"), *SceneName);
        return;
    }
    
    // 生成場景縮略圖
    FGeneratedScene& Scene = GeneratedScenes[SceneName];
    Scene.ThumbnailPath = FString::Printf(TEXT("%s/Thumbnail.png"), *Scene.ScenePath);
    
    UE_LOG(LogTemp, Log, TEXT("Generated thumbnail for scene: %s"), *SceneName);
}

float UMingAutoSceneGenerator::GetSceneComplexityScore(const FString& SceneName) const
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        return 0.0f;
    }
    
    const FGeneratedScene& Scene = GeneratedScenes[SceneName];
    
    // 計算複雜度分數
    float AssetCount = Scene.GeneratedAssets.Num();
    float AssetTypes = Scene.GeneratedAssets.Num();
    float ComplexityScore = (AssetCount * 0.3f) + (AssetTypes * 0.7f);
    
    return FMath::Clamp(ComplexityScore, 0.0f, 100.0f);
}

TArray<EAIContentType> UMingAutoSceneGenerator::GetSceneAssetTypes(const FString& SceneName) const
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        return TArray<EAIContentType>();
    }
    
    const FGeneratedScene& Scene = GeneratedScenes[SceneName];
    TArray<EAIContentType> AssetTypes;
    
    for (const auto& AssetPair : Scene.GeneratedAssets)
    {
        AssetTypes.Add(AssetPair.Key);
    }
    
    return AssetTypes;
}

int32 UMingAutoSceneGenerator::GetSceneAssetCount(const FString& SceneName) const
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        return 0;
    }
    
    return GeneratedScenes[SceneName].GeneratedAssets.Num();
}

float UMingAutoSceneGenerator::GetSceneGenerationTime(const FString& SceneName) const
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        return 0.0f;
    }
    
    return EstimateGenerationTime(FSceneRequirement());
}

void UMingAutoSceneGenerator::BatchGenerateScenes(const TArray<FSceneRequirement>& RequirementsList)
{
    for (const FSceneRequirement& Requirements : RequirementsList)
    {
        GenerateSceneAsync(Requirements);
    }
}

void UMingAutoSceneGenerator::BatchExportScenes(const TArray<FString>& SceneNames, const FString& ExportFormat)
{
    for (const FString& SceneName : SceneNames)
    {
        FString ExportPath = FString::Printf(TEXT("%s.%s"), *SceneName, *ExportFormat);
        ExportScene(SceneName, ExportPath);
    }
}

void UMingAutoSceneGenerator::OptimizeAllScenes()
{
    for (auto& ScenePair : GeneratedScenes)
    {
        FGeneratedScene& Scene = ScenePair.Value;
        
        // 優化場景資產
        if (AIContentManager)
        {
            AIContentManager->OptimizeAssets();
            AIContentManager->CompressAssets();
        }
    }
    
    UE_LOG(LogTemp, Log, TEXT("Optimized all generated scenes"));
}

void UMingAutoSceneGenerator::SaveSceneTemplate(const FString& TemplateName, const FSceneRequirement& Requirements)
{
    SceneTemplates.Add(TemplateName, Requirements);
    
    UE_LOG(LogTemp, Log, TEXT("Saved scene template: %s"), *TemplateName);
}

FSceneRequirement UMingAutoSceneGenerator::LoadSceneTemplate(const FString& TemplateName)
{
    if (SceneTemplates.Contains(TemplateName))
    {
        return SceneTemplates[TemplateName];
    }
    
    return FSceneRequirement();
}

TArray<FString> UMingAutoSceneGenerator::GetAvailableTemplates() const
{
    TArray<FString> TemplateNames;
    
    for (const auto& TemplatePair : SceneTemplates)
    {
        TemplateNames.Add(TemplatePair.Key);
    }
    
    return TemplateNames;
}

TArray<FSceneRequirement> UMingAutoSceneGenerator::GenerateSceneVariants(const FSceneRequirement& BaseRequirements, int32 VariantCount)
{
    TArray<FSceneRequirement> Variants;
    
    for (int32 i = 0; i < VariantCount; ++i)
    {
        FSceneRequirement Variant = BaseRequirements;
        
        // 創建變體
        Variant.Description = FString::Printf(TEXT("%s - Variant %d"), *BaseRequirements.Description, i + 1);
        
        // 隨機調整一些參數
        if (i % 2 == 0)
        {
            Variant.Style = static_cast<ESceneStyle>((static_cast<int32>(BaseRequirements.Style) + 1) % 10);
        }
        
        if (i % 3 == 0)
        {
            Variant.Complexity = static_cast<ESceneComplexity>((static_cast<int32>(BaseRequirements.Complexity) + 1) % 4);
        }
        
        Variants.Add(Variant);
    }
    
    return Variants;
}

void UMingAutoSceneGenerator::GenerateSceneVariantsAsync(const FSceneRequirement& BaseRequirements, int32 VariantCount)
{
    TArray<FSceneRequirement> Variants = GenerateSceneVariants(BaseRequirements, VariantCount);
    BatchGenerateScenes(Variants);
}

TArray<FSceneRequirement> UMingAutoSceneGenerator::GetRecommendedScenes(const FString& Context)
{
    TArray<FSceneRequirement> Recommendations;
    
    // 基於上下文生成推薦場景
    if (Context.Contains(TEXT("battle")) || Context.Contains(TEXT("war")))
    {
        Recommendations.Add(GetBattleSceneTemplate(TEXT("Epic Ming dynasty battle")));
    }
    
    if (Context.Contains(TEXT("village")) || Context.Contains(TEXT("peaceful")))
    {
        Recommendations.Add(GetVillageSceneTemplate(TEXT("Peaceful Ming village")));
    }
    
    if (Context.Contains(TEXT("palace")) || Context.Contains(TEXT("imperial")))
    {
        Recommendations.Add(GetPalaceSceneTemplate(TEXT("Magnificent Ming palace")));
    }
    
    if (Context.Contains(TEXT("nature")) || Context.Contains(TEXT("landscape")))
    {
        Recommendations.Add(GetNatureSceneTemplate(ESceneType::Forest, TEXT("Beautiful Chinese landscape")));
    }
    
    return Recommendations;
}

FSceneRequirement UMingAutoSceneGenerator::OptimizeSceneRequirements(const FSceneRequirement& Requirements)
{
    FSceneRequirement Optimized = Requirements;
    
    // 優化資產需求
    if (Optimized.RequiredAssets.Num() > 8)
    {
        // 限制資產類型數量
        Optimized.RequiredAssets.SetNum(8);
    }
    
    // 優化複雜度
    if (Optimized.Complexity == ESceneComplexity::Epic && Optimized.RequiredAssets.Num() < 4)
    {
        Optimized.Complexity = ESceneComplexity::Complex;
    }
    
    // 優化持續時間
    if (Optimized.Duration > 120.0f)
    {
        Optimized.Duration = 120.0f;
    }
    
    return Optimized;
}

float UMingAutoSceneGenerator::GetAverageSceneGenerationTime() const
{
    if (TotalSceneCount > 0)
    {
        return TotalGenerationTime / TotalSceneCount;
    }
    return 0.0f;
}

int32 UMingAutoSceneGenerator::GetActiveSceneGenerations() const
{
    return ActiveGenerations.Num();
}

int32 UMingAutoSceneGenerator::GetTotalGeneratedScenes() const
{
    return TotalSceneCount;
}

void UMingAutoSceneGenerator::ClearSceneCache()
{
    GeneratedScenes.Empty();
    ActiveGenerations.Empty();
    
    UE_LOG(LogTemp, Log, TEXT("Cleared scene cache"));
}

void UMingAutoSceneGenerator::SetDefaultQuality(EGenerationQuality Quality)
{
    DefaultQuality = Quality;
    
    if (AIContentManager)
    {
        AIContentManager->SetQualitySettings(Quality);
    }
}

void UMingAutoSceneGenerator::SetDefaultStyle(ESceneStyle Style)
{
    DefaultStyle = Style;
}

void UMingAutoSceneGenerator::SetOutputDirectory(const FString& Directory)
{
    OutputDirectory = Directory;
    
    if (AIContentManager)
    {
        AIContentManager->SetOutputSettings(Directory, true);
    }
}

void UMingAutoSceneGenerator::ProcessSceneGeneration(const FString& SceneName, const FSceneRequirement& Requirements)
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        return;
    }
    
    FGeneratedScene& Scene = GeneratedScenes[SceneName];
    
    try
    {
        // 更新進度
        UpdateGenerationProgress(SceneName, 0.1f);
        
        // 生成所需資產
        GenerateRequiredAssets(SceneName, Requirements);
        
        UpdateGenerationProgress(SceneName, 0.7f);
        
        // 設置場景配置
        SetupSceneConfiguration(SceneName, Requirements);
        
        UpdateGenerationProgress(SceneName, 0.9f);
        
        // 生成縮略圖
        GenerateSceneThumbnail(SceneName);
        
        UpdateGenerationProgress(SceneName, 1.0f);
        
        // 完成生成
        CompleteSceneGeneration(SceneName, true);
    }
    catch (...)
    {
        CompleteSceneGeneration(SceneName, false);
    }
}

void UMingAutoSceneGenerator::GenerateRequiredAssets(const FString& SceneName, const FSceneRequirement& Requirements)
{
    if (!AIContentManager)
    {
        return;
    }
    
    FGeneratedScene& Scene = GeneratedScenes[SceneName];
    
    for (EAIContentType AssetType : Requirements.RequiredAssets)
    {
        if (Requirements.AssetPrompts.Contains(AssetType))
        {
            FString Prompt = Requirements.AssetPrompts[AssetType];
            FString AssetPath = AIContentManager->GenerateContent(AssetType, Prompt, DefaultQuality);
            
            if (!AssetPath.IsEmpty())
            {
                Scene.GeneratedAssets.Add(AssetType, AssetPath);
            }
        }
    }
}

void UMingAutoSceneGenerator::SetupSceneConfiguration(const FString& SceneName, const FSceneRequirement& Requirements)
{
    FGeneratedScene& Scene = GeneratedScenes[SceneName];
    
    // 創建場景配置
    Scene.SceneConfiguration = CreateSceneConfiguration(Requirements);
    
    if (AIContentManager)
    {
        AIContentManager->GenerateGameScene(Requirements.Description, Scene.SceneConfiguration);
    }
}

void UMingAutoSceneGenerator::CompleteSceneGeneration(const FString& SceneName, bool bSuccess)
{
    if (!GeneratedScenes.Contains(SceneName))
    {
        return;
    }
    
    FGeneratedScene& Scene = GeneratedScenes[SceneName];
    Scene.bIsComplete = bSuccess;
    
    if (bSuccess)
    {
        TotalSceneCount++;
        NotifySceneGenerationCompleted(SceneName, Scene);
    }
    else
    {
        NotifySceneGenerationFailed(SceneName, TEXT("Scene generation failed"));
    }
    
    // 從活動生成列表中移除
    ActiveGenerations.Remove(SceneName);
}

void UMingAutoSceneGenerator::UpdateGenerationProgress(const FString& SceneName, float Progress)
{
    if (GeneratedScenes.Contains(SceneName))
    {
        GeneratedScenes[SceneName].GenerationProgress = Progress;
        NotifySceneGenerationProgress(SceneName, Progress);
    }
}

void UMingAutoSceneGenerator::NotifySceneGenerationStarted(const FString& SceneName, const FSceneRequirement& Requirements)
{
    OnSceneGenerationStarted.Broadcast(SceneName, Requirements);
}

void UMingAutoSceneGenerator::NotifySceneGenerationProgress(const FString& SceneName, float Progress)
{
    OnSceneGenerationProgress.Broadcast(SceneName, Progress);
}

void UMingAutoSceneGenerator::NotifySceneGenerationCompleted(const FString& SceneName, const FGeneratedScene& GeneratedScene)
{
    OnSceneGenerationCompleted.Broadcast(SceneName, GeneratedScene);
}

void UMingAutoSceneGenerator::NotifySceneGenerationFailed(const FString& SceneName, const FString& ErrorMessage)
{
    OnSceneGenerationFailed.Broadcast(SceneName, ErrorMessage);
}

FString UMingAutoSceneGenerator::GenerateUniqueSceneName() const
{
    return FString::Printf(TEXT("AutoScene_%s"), *FDateTime::Now().ToString());
}

FString UMingAutoSceneGenerator::GetScenePath(const FString& SceneName) const
{
    return FString::Printf(TEXT("%s%s/"), *OutputDirectory, *SceneName);
}

FSceneRequirement UMingAutoSceneGenerator::CreateDefaultRequirements(ESceneType SceneType) const
{
    switch (SceneType)
    {
        case ESceneType::Battle:
            return GetBattleSceneTemplate(TEXT(""));
        case ESceneType::Village:
            return GetVillageSceneTemplate(TEXT(""));
        case ESceneType::Palace:
            return GetPalaceSceneTemplate(TEXT(""));
        case ESceneType::Forest:
            return GetNatureSceneTemplate(ESceneType::Forest, TEXT(""));
        case ESceneType::Mountain:
            return GetNatureSceneTemplate(ESceneType::Mountain, TEXT(""));
        case ESceneType::River:
            return GetNatureSceneTemplate(ESceneType::River, TEXT(""));
        case ESceneType::Desert:
            return GetNatureSceneTemplate(ESceneType::Desert, TEXT(""));
        default:
            return FSceneRequirement();
    }
}

TArray<EAIContentType> UMingAutoSceneGenerator::DetermineRequiredAssets(const FSceneRequirement& Requirements) const
{
    TArray<EAIContentType> RequiredAssets;
    
    if (Requirements.bHasCharacters)
    {
        RequiredAssets.Add(EAIContentType::Mesh);
        RequiredAssets.Add(EAIContentType::Texture);
        RequiredAssets.Add(EAIContentType::Material);
        RequiredAssets.Add(EAIContentType::Animation);
    }
    
    if (Requirements.bHasBuildings)
    {
        RequiredAssets.Add(EAIContentType::Mesh);
        RequiredAssets.Add(EAIContentType::Texture);
        RequiredAssets.Add(EAIContentType::Material);
    }
    
    if (Requirements.bHasEnvironment)
    {
        RequiredAssets.Add(EAIContentType::Image);
        RequiredAssets.Add(EAIContentType::Texture);
        RequiredAssets.Add(EAIContentType::Material);
    }
    
    if (Requirements.bHasEffects)
    {
        RequiredAssets.Add(EAIContentType::SoundEffect);
        RequiredAssets.Add(EAIContentType::Music);
    }
    
    // 始終包含圖像
    if (!RequiredAssets.Contains(EAIContentType::Image))
    {
        RequiredAssets.Add(EAIContentType::Image);
    }
    
    return RequiredAssets;
}

TMap<EAIContentType, FString> UMingAutoSceneGenerator::GenerateAssetPrompts(const FSceneRequirement& Requirements) const
{
    TMap<EAIContentType, FString> AssetPrompts;
    
    // 基於場景類型和描述生成提示
    FString BasePrompt = Requirements.Description;
    
    AssetPrompts.Add(EAIContentType::Image, FString::Printf(TEXT("%s, %s style"), *BasePrompt, *GetStyleString(Requirements.Style)));
    AssetPrompts.Add(EAIContentType::Music, FString::Printf(TEXT("Background music for %s"), *BasePrompt));
    AssetPrompts.Add(EAIContentType::SoundEffect, FString::Printf(TEXT("Sound effects for %s"), *BasePrompt));
    
    if (Requirements.bHasCharacters)
    {
        AssetPrompts.Add(EAIContentType::Mesh, FString::Printf(TEXT("Character model for %s"), *BasePrompt));
        AssetPrompts.Add(EAIContentType::Texture, FString::Printf(TEXT("Character texture for %s"), *BasePrompt));
        AssetPrompts.Add(EAIContentType::Material, FString::Printf(TEXT("Character material for %s"), *BasePrompt));
        AssetPrompts.Add(EAIContentType::Animation, FString::Printf(TEXT("Character animation for %s"), *BasePrompt));
    }
    
    if (Requirements.bHasBuildings)
    {
        AssetPrompts.Add(EAIContentType::Mesh, FString::Printf(TEXT("Building model for %s"), *BasePrompt));
        AssetPrompts.Add(EAIContentType::Texture, FString::Printf(TEXT("Building texture for %s"), *BasePrompt));
        AssetPrompts.Add(EAIContentType::Material, FString::Printf(TEXT("Building material for %s"), *BasePrompt));
    }
    
    return AssetPrompts;
}

FAISceneConfiguration UMingAutoSceneGenerator::CreateSceneConfiguration(const FSceneRequirement& Requirements) const
{
    FAISceneConfiguration SceneConfig;
    
    SceneConfig.SceneName = FString::Printf(TEXT("AutoScene_%s"), *FDateTime::Now().ToString());
    SceneConfig.LocationDescription = Requirements.Description;
    SceneConfig.TimeOfDay = GetTimeOfDayFromComplexity(Requirements.Complexity);
    SceneConfig.Weather = GetWeatherFromStyle(Requirements.Style);
    SceneConfig.Mood = GetMoodFromSceneType(Requirements.SceneType);
    SceneConfig.RenderQuality = GetRenderQualityFromComplexity(Requirements.Complexity);
    
    // 設置後處理效果
    SceneConfig.bEnablePostProcessing = Requirements.Complexity >= ESceneComplexity::Medium;
    SceneConfig.bEnableBloom = Requirements.Complexity >= ESceneComplexity::Complex;
    SceneConfig.bEnableLensFlare = Requirements.Complexity == ESceneComplexity::Epic;
    SceneConfig.bEnableVolumetricFog = Requirements.bHasEnvironment;
    
    return SceneConfig;
}

float UMingAutoSceneGenerator::EstimateGenerationTime(const FSceneRequirement& Requirements) const
{
    float BaseTime = 30.0f; // 基礎時間
    
    // 根據複雜度調整
    switch (Requirements.Complexity)
    {
        case ESceneComplexity::Simple:
            BaseTime *= 0.5f;
            break;
        case ESceneComplexity::Medium:
            BaseTime *= 1.0f;
            break;
        case ESceneComplexity::Complex:
            BaseTime *= 2.0f;
            break;
        case ESceneComplexity::Epic:
            BaseTime *= 3.0f;
            break;
    }
    
    // 根據資產數量調整
    BaseTime += Requirements.RequiredAssets.Num() * 5.0f;
    
    return BaseTime;
}

void UMingAutoSceneGenerator::LoadDefaultTemplates()
{
    // 加載默認場景模板
    SaveSceneTemplate(TEXT("Battle"), GetBattleSceneTemplate(TEXT("")));
    SaveSceneTemplate(TEXT("Village"), GetVillageSceneTemplate(TEXT("")));
    SaveSceneTemplate(TEXT("Palace"), GetPalaceSceneTemplate(TEXT("")));
    SaveSceneTemplate(TEXT("Forest"), GetNatureSceneTemplate(ESceneType::Forest, TEXT("")));
    SaveSceneTemplate(TEXT("Mountain"), GetNatureSceneTemplate(ESceneType::Mountain, TEXT("")));
}

void UMingAutoSceneGenerator::SaveSceneData()
{
    // 實現場景數據保存
    FString SceneDataPath = FPaths::ProjectDir() / TEXT("Saved/AutoScenes/Scenes.json");
    
    // 這裡可以實現JSON序列化保存
}

void UMingAutoSceneGenerator::LoadSceneData()
{
    // 實現場景數據加載
    FString SceneDataPath = FPaths::ProjectDir() / TEXT("Saved/AutoScenes/Scenes.json");
    
    // 這裡可以實現JSON反序列化加載
}

// 輔助函數實現
FString UMingAutoSceneGenerator::GetStyleString(ESceneStyle Style) const
{
    switch (Style)
    {
        case ESceneStyle::Realistic: return TEXT("realistic");
        case ESceneStyle::Stylized: return TEXT("stylized");
        case ESceneStyle::Cartoon: return TEXT("cartoon");
        case ESceneStyle::Watercolor: return TEXT("watercolor");
        case ESceneStyle::Ink: return TEXT("ink painting");
        case ESceneStyle::OilPainting: return TEXT("oil painting");
        case ESceneStyle::PixelArt: return TEXT("pixel art");
        case ESceneStyle::LowPoly: return TEXT("low poly");
        case ESceneStyle::CelShaded: return TEXT("cel shaded");
        case ESceneStyle::Photorealistic: return TEXT("photorealistic");
        default: return TEXT("realistic");
    }
}

ETimeOfDay UMingAutoSceneGenerator::GetTimeOfDayFromComplexity(ESceneComplexity Complexity) const
{
    switch (Complexity)
    {
        case ESceneComplexity::Simple:
            return ETimeOfDay::Morning;
        case ESceneComplexity::Medium:
            return ETimeOfDay::Afternoon;
        case ESceneComplexity::Complex:
            return ETimeOfDay::Dusk;
        case ESceneComplexity::Epic:
            return ETimeOfDay::Night;
        default:
            return ETimeOfDay::Morning;
    }
}

EWeatherType UMingAutoSceneGenerator::GetWeatherFromStyle(ESceneStyle Style) const
{
    switch (Style)
    {
        case ESceneStyle::Realistic:
        case ESceneStyle::Photorealistic:
            return EWeatherType::Clear;
        case ESceneStyle::Stylized:
        case ESceneStyle::Cartoon:
            return EWeatherType::Clear;
        case ESceneStyle::Watercolor:
        case ESceneStyle::Ink:
            return EWeatherType::Foggy;
        case ESceneStyle::OilPainting:
            return EWeatherType::Cloudy;
        default:
            return EWeatherType::Clear;
    }
}

ESceneMood UMingAutoSceneGenerator::GetMoodFromSceneType(ESceneType SceneType) const
{
    switch (SceneType)
    {
        case ESceneType::Battle:
        case ESceneType::Battlefield:
            return ESceneMood::Dramatic;
        case ESceneType::Village:
            return ESceneMood::Peaceful;
        case ESceneType::Palace:
        case ESceneType::Temple:
            return ESceneMood::Epic;
        case ESceneType::Forest:
        case ESceneType::Mountain:
        case ESceneType::River:
            return ESceneMood::Peaceful;
        case ESceneType::Desert:
            return ESceneMood::Mysterious;
        case ESceneType::City:
            return ESceneMood::Joyful;
        default:
            return ESceneMood::Peaceful;
    }
}

ERenderQuality UMingAutoSceneGenerator::GetRenderQualityFromComplexity(ESceneComplexity Complexity) const
{
    switch (Complexity)
    {
        case ESceneComplexity::Simple:
            return ERenderQuality::Low;
        case ESceneComplexity::Medium:
            return ERenderQuality::Medium;
        case ESceneComplexity::Complex:
            return ERenderQuality::High;
        case ESceneComplexity::Epic:
            return ERenderQuality::Cinematic;
        default:
            return ERenderQuality::Medium;
    }
}
